### ISSUE TITLE
[8.0] Are you planning a port to 8.0 for this module?

### ISSUE THREAD

**Issue by lukebranch** [colinnewell/openerp_elastic_product_search#1]
@colinnewell ,

Thanks for building this, it looks like a very useful module, and perhaps one that could be extended to handle website_sale search, forum search, blog search, etc. as well.

Do you have any plans to port this module to 8.0? Also, have you seen this module?:

https://github.com/OpenSur/Odoo_addons/tree/master/website_search

the above module plugged into Lucene/ElasticSearch would be an incredibly useful module for website all-in-one search.

**Comment by colinnewell** [comment]
@lukebranch this was just a proof of concept and a chance to learn more about OpenERP so not really.  If someone wants to fork it and make use of it that's cool of course though.

I hadn't seen that module before.  I assume it's not too great for performance because it performs like comparisons although that it tweakable with indexes.  It might be better to look at Postgres's full text search facilities though.  There is another issue that would make me recommend that you don't use that module currently.  I've reported it directly to them.

See http://www.depesz.com/2011/02/19/waiting-for-9-1-faster-likeilike/ for making like searches quicker.  We have added them to a large OpenERP install for a particular field that was getting searched a lot and it made a significant boost to the performance of that lookup.

**Comment by lukebranch** [comment]
@colinnewell ,

Thanks for the detailed reply, i'll definitely look into the article you suggested.

If it's alright with you I may fork your project and try and build on it to handle website_sale search among other things. I've been considering either using Elastic, SolR, or Sphinx for frontend website search for Odoo to offload some of the load and improve on the performance and accuracy of FTS for the frontend.

I've come across the project above (OpenSUR), and another by Akretion for SolR:

https://github.com/akretion/solerp

i'll take a look at your code in more detail along with the post you mentioned above and close this issue. Thanks for your help!

**Comment by colinnewell** [comment]
That's fine of course.  Good luck with it.
